[package]
name = "trains-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cgmath = "0.18.0"
eframe = "0.31.1"
nom = "8.0.0"
ordered-float = "5.0.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
